/**
 * Subscription Management Screen
 * 
 * This screen allows users to view and manage their subscription status,
 * including upgrading, downgrading, and canceling subscriptions.
 */

import React, { useState, useEffect, useMemo, useRef } from 'react';
import {
  View,
  ScrollView,
  StyleSheet,
  Alert,
  TouchableOpacity,
  RefreshControl,
  Image,
  Text,
  Platform,
  Linking,
  AppState,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { MaterialCommunityIcons as Icon } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';

import { useSubscription } from '../../../src/hooks/useSubscription';
import { RevenueCatService, SubscriptionInfo } from '../../../src/services/subscription/RevenueCatService';

// Clean Design System
const colors = {
  primary: '#FF6B35',
  primaryDark: '#E55A2B',
  text: '#FFFFFF',
  textSecondary: 'rgba(235, 235, 245, 0.6)',
  success: '#22C55E',
  warning: '#FF9500',
  error: '#FF453A',
};

const PREMIUM_FEATURES = [
  {
    icon: 'dumbbell',
    title: 'Unlimited AI Workouts',
    description: 'Personalized plans generated by Gemini AI',
  },
  {
    icon: 'food-apple',
    title: 'Smart Nutrition Plans',
    description: 'Daily meal plans tailored to your goals',
  },
  {
    icon: 'chart-line-variant',
    title: 'Advanced Analytics',
    description: 'Deep dive into your progress metrics',
  },
  {
    icon: 'dumbbell',
    title: 'Custom Exercises',
    description: 'Build and save your own routines',
  },
];

export default function SubscriptionScreen() {
  const insets = useSafeAreaInsets();
  const { 
    isPremium, 
    subscriptionInfo, 
    refreshSubscription, 
    isLoading: subscriptionLoading 
  } = useSubscription();
  
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [detailedInfo, setDetailedInfo] = useState<SubscriptionInfo | null>(null);
  const previousPlanRef = useRef<string | null>(null);

  // Load subscription info on mount
  useEffect(() => {
    loadDetailedSubscriptionInfo();
  }, []);

  // Refresh subscription info when screen comes into focus
  // This detects changes when user returns from App Store/Play Store after changing plan
  useFocusEffect(
    React.useCallback(() => {
      console.log('[SubscriptionScreen] Screen focused, checking for plan changes...');
      const checkForChanges = async () => {
        try {
          const info = await RevenueCatService.getSubscriptionInfo();
          const currentPlan = info?.productId || 'none';
          const previousPlan = previousPlanRef.current;
          
          if (previousPlan && previousPlan !== currentPlan && currentPlan !== 'none') {
            console.log('[SubscriptionScreen] ✅ Plan change detected!', {
              previous: previousPlan,
              current: currentPlan
            });
            // Refresh subscription status
            await refreshSubscription();
            // Show notification
            Alert.alert(
              'Plan Updated',
              `Your subscription plan has been updated successfully!`,
              [{ text: 'OK' }]
            );
          }
          
            previousPlanRef.current = currentPlan;
            setDetailedInfo(info);
        } catch (error) {
          console.error('[SubscriptionScreen] Error checking for changes:', error);
        }
      };
      
      // Check immediately when screen is focused
      checkForChanges();
      
      // Also check after a short delay (in case user just returned from store)
      const timer = setTimeout(checkForChanges, 1000);
      
      return () => clearTimeout(timer);
    }, [refreshSubscription])
  );

  // Listen for app state changes (when app comes to foreground after user changes plan in store)
  useEffect(() => {
    const subscription = AppState.addEventListener('change', async (nextAppState) => {
      if (nextAppState === 'active') {
        console.log('[SubscriptionScreen] App came to foreground, checking for subscription changes...');
        // Wait a bit for RevenueCat to sync with App Store
        setTimeout(async () => {
          try {
            const info = await RevenueCatService.getSubscriptionInfo();
            const currentPlan = info?.productId || 'none';
            const previousPlan = previousPlanRef.current;
            
            if (previousPlan && previousPlan !== currentPlan && currentPlan !== 'none') {
              console.log('[SubscriptionScreen] ✅ Plan change detected after returning from store!', {
                previous: previousPlan,
                current: currentPlan
              });
              // Refresh subscription status
              await refreshSubscription();
              await loadDetailedSubscriptionInfo();
              // Show notification
              Alert.alert(
                'Plan Updated',
                `Your subscription plan has been updated to ${getPlanName(currentPlan)}!`,
                [{ text: 'OK' }]
              );
            } else {
              // Even if no change detected, refresh to get latest info
              await loadDetailedSubscriptionInfo();
            }
            
            previousPlanRef.current = currentPlan;
          } catch (error) {
            console.error('[SubscriptionScreen] Error checking subscription after app state change:', error);
          }
        }, 2000); // Wait 2 seconds for RevenueCat to sync
      }
    });

    return () => {
      subscription.remove();
    };
  }, [refreshSubscription]);

  // Helper function to get plan name
  const getPlanName = (productId: string | null | undefined): string => {
    if (!productId) return 'Unknown';
    if (productId.includes('lifetime')) return 'Lifetime';
    if (productId.includes('year')) return 'Yearly';
    if (productId.includes('month')) return 'Monthly';
    return 'Premium';
  };

  // AI Coach greeting
  const getAIGreeting = useMemo(() => {
    const hour = new Date().getHours();
    
    let greeting = '';
    let message = '';
    
    if (hour < 12) {
      greeting = 'Good morning';
    } else if (hour < 17) {
      greeting = 'Good afternoon';
    } else {
      greeting = 'Good evening';
    }
    
    message = isPremium 
      ? "You're a Premium member! Manage your subscription here."
      : "Upgrade to Premium to unlock all features.";
    
    return { greeting, message };
  }, [isPremium]);

  const loadDetailedSubscriptionInfo = async () => {
    try {
      const info = await RevenueCatService.getSubscriptionInfo();
      console.log('[SubscriptionScreen] Detailed Info:', JSON.stringify(info, null, 2));
      console.log('[SubscriptionScreen] Expiration Date:', info.expirationDate);
      console.log('[SubscriptionScreen] Will Renew:', info.willRenew);
      console.log('[SubscriptionScreen] Period Type:', info.periodType);
      console.log('[SubscriptionScreen] Product ID:', info.productId);
      
      // Store current plan for change detection
      if (info?.productId) {
        previousPlanRef.current = info.productId;
      }
      
      setDetailedInfo(info);
    } catch (error) {
      console.error('[Subscription] Failed to load detailed info:', error);
    }
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    try {
      await refreshSubscription();
      await loadDetailedSubscriptionInfo();
    } catch (error) {
      console.error('[Subscription] Refresh failed:', error);
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleUpgrade = () => {
    router.push('/paywall');
  };

  const handleManageSubscription = async () => {
    try {
      if (Platform.OS === 'ios') {
        // Open iOS App Store subscription management
        // This opens the App Store subscription management page
        const url = 'https://apps.apple.com/account/subscriptions';
        const canOpen = await Linking.canOpenURL(url);
        if (canOpen) {
          await Linking.openURL(url);
        } else {
          // Fallback: Open App Store settings
          Alert.alert(
            'Manage Subscription',
            'To change your subscription plan:\n\n1. Open Settings app\n2. Tap your Apple ID at the top\n3. Tap Subscriptions\n4. Select GoFitAI\n5. Choose a different plan or cancel',
            [{ text: 'OK' }]
          );
        }
      } else if (Platform.OS === 'android') {
        // Open Google Play Store subscription management
        const url = 'https://play.google.com/store/account/subscriptions';
        const canOpen = await Linking.canOpenURL(url);
        if (canOpen) {
          await Linking.openURL(url);
        } else {
          Alert.alert(
            'Manage Subscription',
            'To change your subscription plan:\n\n1. Open Google Play Store app\n2. Tap Menu (☰)\n3. Tap Subscriptions\n4. Select GoFitAI\n5. Choose a different plan or cancel',
            [{ text: 'OK' }]
          );
        }
      } else {
        Alert.alert(
          'Manage Subscription',
          'To modify or cancel your subscription, please visit the App Store or Google Play Store settings.',
          [{ text: 'OK' }]
        );
      }
    } catch (error) {
      console.error('[Subscription] Failed to open store:', error);
      Alert.alert(
        'Manage Subscription',
        'To change your subscription plan, please visit:\n\n• iOS: Settings → [Your Name] → Subscriptions\n• Android: Google Play Store → Subscriptions',
        [{ text: 'OK' }]
      );
    }
  };


  const formatDate = (dateString: string | null | undefined) => {
    if (!dateString) {
      console.warn('[SubscriptionScreen] No expiration date provided');
      return 'Unknown';
    }
    
    try {
      const date = new Date(dateString);
      if (isNaN(date.getTime())) {
        console.warn('[SubscriptionScreen] Invalid date string:', dateString);
        return 'Unknown';
      }
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    } catch (error) {
      console.error('[SubscriptionScreen] Error formatting date:', error);
      return 'Unknown';
    }
  };

  if (subscriptionLoading) {
    return (
      <View style={[styles.container, styles.centerContent]}>
        <Text style={styles.loadingText}>Loading subscription...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <StatusBar style="light" />
      
      <ScrollView 
        contentContainerStyle={[
          styles.content,
          { paddingTop: insets.top + 16, paddingBottom: 60 + insets.bottom + 20 }
        ]}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={isRefreshing}
            onRefresh={handleRefresh}
            tintColor={colors.primary}
          />
        }
      >
        {/* AI Coach Header */}
        <View style={styles.coachHeader}>
          <TouchableOpacity 
            onPress={() => router.back()} 
            style={styles.backButton}
            activeOpacity={0.8}
          >
            <Icon name="arrow-left" size={22} color={colors.text} />
          </TouchableOpacity>
          <View style={styles.coachAvatarContainer}>
            <Image
              source={require('../../../assets/mascot.png')}
              style={styles.coachAvatar}
            />
            <View style={styles.coachOnlineIndicator} />
          </View>
          <View style={styles.coachTextContainer}>
            <Text style={styles.coachGreeting}>{getAIGreeting.greeting}</Text>
            <Text style={styles.coachMessage}>{getAIGreeting.message}</Text>
          </View>
        </View>

        {/* Status Card */}
        <View style={styles.statusCard}>
          <View style={styles.statusHeader}>
            <View style={[
              styles.statusIconContainer,
              { backgroundColor: isPremium ? 'rgba(255, 107, 53, 0.12)' : 'rgba(255, 255, 255, 0.06)' }
            ]}>
              <Icon 
                name={isPremium ? 'crown' : 'account'} 
                size={24} 
                color={isPremium ? colors.primary : colors.textSecondary} 
              />
            </View>
            <View style={styles.statusTextContainer}>
              <Text style={styles.statusLabel}>Current Plan</Text>
              <Text style={styles.statusTitle}>
                {isPremium ? 'Premium Member' : 'Free Plan'}
              </Text>
            </View>
          </View>

          {isPremium && detailedInfo && (
            <View style={styles.premiumInfo}>
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>
                  {(() => {
                    if (detailedInfo.periodType === 'lifetime') return 'Expires on';
                    if (!detailedInfo.expirationDate) return 'Renews on';
                    
                    const expDate = new Date(detailedInfo.expirationDate);
                    const purchaseDate = detailedInfo.originalPurchaseDate 
                      ? new Date(detailedInfo.originalPurchaseDate) 
                      : null;
                    
                    if (purchaseDate) {
                      const daysDiff = Math.floor((expDate.getTime() - purchaseDate.getTime()) / (1000 * 60 * 60 * 24));
                      if (daysDiff <= 7 && daysDiff > 0) {
                        return 'Trial ends on';
                      }
                    }
                    return 'Renews on';
                  })()}
                </Text>
                <Text style={styles.infoValue}>
                  {detailedInfo.expirationDate 
                    ? formatDate(detailedInfo.expirationDate)
                    : detailedInfo.periodType === 'lifetime'
                      ? 'Never'
                      : detailedInfo.willRenew
                        ? 'Auto-renewing'
                        : 'Unknown'}
                </Text>
              </View>
              <View style={styles.divider} />
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Plan Type</Text>
                <Text style={styles.infoValue}>
                  {detailedInfo.productId?.includes('lifetime') ? 'Lifetime' : 
                   detailedInfo.productId?.includes('year') ? 'Yearly' : 'Monthly'}
                </Text>
              </View>
              {detailedInfo.periodType === 'monthly' && (
                <>
                  <View style={styles.divider} />
                  <View style={styles.switchInfo}>
                    <Icon name="information" size={16} color={colors.textSecondary} />
                    <Text style={styles.switchInfoText}>
                      Switch to Lifetime to save long-term. Your monthly subscription will be cancelled (no refund for remaining time).
                    </Text>
                  </View>
                </>
              )}
            </View>
          )}

          {!isPremium && (
            <Text style={styles.freeDescription}>
              Upgrade to unlock unlimited potential and accelerate your fitness journey.
            </Text>
          )}
        </View>

        {/* Features List */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Premium Features</Text>
          <View style={styles.featuresGrid}>
            {PREMIUM_FEATURES.map((feature, index) => (
              <View key={index} style={styles.featureItem}>
                <View style={styles.featureIconContainer}>
                  <Icon 
                    name={feature.icon as any} 
                    size={20} 
                    color={isPremium ? colors.primary : colors.textSecondary} 
                  />
                </View>
                <View style={styles.featureTextContent}>
                  <Text style={styles.featureTitle}>{feature.title}</Text>
                  <Text style={styles.featureDescription}>{feature.description}</Text>
                </View>
                {isPremium ? (
                   <Icon name="check-circle" size={20} color={colors.success} />
                ) : (
                   <Icon name="lock" size={20} color={colors.textSecondary} />
                )}
              </View>
            ))}
          </View>
        </View>

        {/* Actions */}
        <View style={styles.actionContainer}>
          {!isPremium ? (
            <TouchableOpacity 
              style={styles.upgradeButton}
              onPress={handleUpgrade}
              activeOpacity={0.8}
            >
              <LinearGradient
                colors={[colors.primary, colors.primaryDark]}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={styles.gradientButton}
              >
                <Text style={styles.upgradeButtonText}>Upgrade to Premium</Text>
                <Icon name="arrow-forward" size={20} color={colors.text} />
              </LinearGradient>
            </TouchableOpacity>
          ) : (
            <>
              {detailedInfo && detailedInfo.periodType === 'monthly' && (
                <TouchableOpacity 
                  style={styles.upgradeButton}
                  onPress={handleUpgrade}
                  activeOpacity={0.8}
                >
                  <LinearGradient
                    colors={[colors.primary, colors.primaryDark]}
                    start={{ x: 0, y: 0 }}
                    end={{ x: 1, y: 0 }}
                    style={styles.gradientButton}
                  >
                    <Text style={styles.upgradeButtonText}>Switch to Lifetime</Text>
                    <Icon name="crown" size={20} color={colors.text} />
                  </LinearGradient>
                </TouchableOpacity>
              )}
              
              <TouchableOpacity 
                style={styles.manageButton}
                onPress={handleManageSubscription}
                activeOpacity={0.8}
              >
                <Text style={styles.manageButtonText}>Manage Subscription</Text>
              </TouchableOpacity>
            </>
          )}
        </View>
        
        {/* Footer Info */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Subscriptions auto-renew unless canceled at least 24 hours before the end of the current period.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: colors.textSecondary,
    fontSize: 16,
  },
  content: {
    paddingHorizontal: 20,
  },

  // AI Coach Header
  coachHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingTop: 8,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  coachAvatarContainer: {
    position: 'relative',
    marginRight: 14,
  },
  coachAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    resizeMode: 'contain',
  },
  coachOnlineIndicator: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: '#000000',
  },
  coachTextContainer: {
    flex: 1,
  },
  coachGreeting: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  coachMessage: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },

  // Status Card
  statusCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  statusTextContainer: {
    flex: 1,
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  statusTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  premiumInfo: {
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  infoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 12,
  },
  freeDescription: {
    marginTop: 12,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 16,
  },
  featuresGrid: {
    gap: 10,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    gap: 12,
  },
  featureIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  featureTextContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 2,
  },
  featureDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  actionContainer: {
    gap: 12,
    marginBottom: 24,
  },
  upgradeButton: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  gradientButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  upgradeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  manageButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  manageButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  footer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  footerText: {
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  switchInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
    gap: 8,
  },
  switchInfoText: {
    flex: 1,
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
});