/**
 * Subscription Management Screen
 * 
 * This screen allows users to view and manage their subscription status,
 * including upgrading, downgrading, and canceling subscriptions.
 */

import React, { useState, useEffect } from 'react';
import {
  View,
  ScrollView,
  StyleSheet,
  Alert,
  Pressable,
  RefreshControl,
  Dimensions,
} from 'react-native';
import {
  Text,
  ActivityIndicator,
  IconButton,
} from 'react-native-paper';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';

import { useSubscription } from '../../../src/hooks/useSubscription';
import { RevenueCatService, SubscriptionInfo } from '../../../src/services/subscription/RevenueCatService';
import { colors } from '../../../src/styles/colors';

const PREMIUM_FEATURES = [
  {
    icon: 'fitness',
    title: 'Unlimited AI Workouts',
    description: 'Personalized plans generated by Gemini AI',
  },
  {
    icon: 'nutrition',
    title: 'Smart Nutrition Plans',
    description: 'Daily meal plans tailored to your goals',
  },
  {
    icon: 'analytics',
    title: 'Advanced Analytics',
    description: 'Deep dive into your progress metrics',
  },
  {
    icon: 'barbell',
    title: 'Custom Exercises',
    description: 'Build and save your own routines',
  },
];

export default function SubscriptionScreen() {
  const insets = useSafeAreaInsets();
  const { 
    isPremium, 
    subscriptionInfo, 
    refreshSubscription, 
    restorePurchases,
    isLoading: subscriptionLoading 
  } = useSubscription();
  
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [detailedInfo, setDetailedInfo] = useState<SubscriptionInfo | null>(null);

  useEffect(() => {
    loadDetailedSubscriptionInfo();
  }, []);

  const loadDetailedSubscriptionInfo = async () => {
    try {
      const info = await RevenueCatService.getSubscriptionInfo();
      setDetailedInfo(info);
    } catch (error) {
      console.error('[Subscription] Failed to load detailed info:', error);
    }
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    try {
      await refreshSubscription();
      await loadDetailedSubscriptionInfo();
    } catch (error) {
      console.error('[Subscription] Refresh failed:', error);
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleUpgrade = () => {
    router.push('/paywall');
  };

  const handleManageSubscription = () => {
    Alert.alert(
      'Manage Subscription',
      'To modify or cancel your subscription, please visit the App Store or Google Play Store.',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Open Store', 
          onPress: () => {
            // This is just informative in simulator, would deep link in real app
            Alert.alert('Info', 'This would open your device app store settings.');
          }
        },
      ]
    );
  };

  const handleRestorePurchases = async () => {
    try {
      await restorePurchases();
      Alert.alert('Success', 'Purchases restored successfully.');
    } catch (error) {
      Alert.alert('Error', 'Failed to restore purchases. Please try again.');
      console.error('[Subscription] Restore failed:', error);
    }
  };

  const formatDate = (dateString: string | null | undefined) => {
    if (!dateString) return 'Unknown';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  if (subscriptionLoading) {
    return (
      <View style={[styles.container, styles.centerContent]}>
        <ActivityIndicator size="large" color={colors.primary} />
        <Text style={styles.loadingText}>Loading subscription...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <StatusBar style="light" />
      
      {/* Header */}
      <View style={[styles.header, { paddingTop: insets.top + 10 }]}>
        <IconButton 
          icon="arrow-left" 
          size={24} 
          iconColor={colors.text}
          onPress={() => router.back()} 
          style={styles.backButton} 
        />
        <Text style={styles.headerTitle}>Subscription</Text>
        <View style={{ width: 48 }} /> 
      </View>

      <ScrollView 
        style={styles.content}
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl
            refreshing={isRefreshing}
            onRefresh={handleRefresh}
            tintColor={colors.primary}
            colors={[colors.primary]}
          />
        }
      >
        {/* Status Card */}
        <View style={styles.cardContainer}>
          <LinearGradient
            colors={isPremium ? colors.gradients.primary : [colors.secondaryLight, colors.secondary]}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
            style={styles.statusCard}
          >
            <View style={styles.statusHeader}>
              <View>
                <Text style={styles.statusLabel}>CURRENT PLAN</Text>
                <Text style={styles.statusTitle}>
                  {isPremium ? 'Premium Member' : 'Free Plan'}
                </Text>
              </View>
              <View style={[
                styles.iconContainer, 
                { backgroundColor: isPremium ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.1)' }
              ]}>
                <Ionicons 
                  name={isPremium ? 'diamond' : 'person'} 
                  size={24} 
                  color={colors.text} 
                />
              </View>
            </View>

            {isPremium && detailedInfo && (
              <View style={styles.premiumInfo}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Renews on</Text>
                  <Text style={styles.infoValue}>{formatDate(detailedInfo.expirationDate)}</Text>
                </View>
                <View style={styles.divider} />
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Plan Type</Text>
                  <Text style={styles.infoValue}>
                    {detailedInfo.productId?.includes('year') ? 'Yearly' : 'Monthly'}
                  </Text>
                </View>
              </View>
            )}

            {!isPremium && (
              <Text style={styles.freeDescription}>
                Upgrade to unlock unlimited potential and accelerate your fitness journey.
              </Text>
            )}
          </LinearGradient>
        </View>

        {/* Features List */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Premium Features</Text>
          <View style={styles.featuresGrid}>
            {PREMIUM_FEATURES.map((feature, index) => (
              <View key={index} style={styles.featureItem}>
                <View style={[styles.featureIconBox, { backgroundColor: isPremium ? colors.primary + '20' : colors.secondaryLight }]}>
                  <Ionicons 
                    name={feature.icon as any} 
                    size={24} 
                    color={isPremium ? colors.primary : colors.gray} 
                  />
                </View>
                <View style={styles.featureTextContent}>
                  <Text style={styles.featureTitle}>{feature.title}</Text>
                  <Text style={styles.featureDescription}>{feature.description}</Text>
                </View>
                {isPremium ? (
                   <Ionicons name="checkmark-circle" size={20} color={colors.success} />
                ) : (
                   <Ionicons name="lock-closed-outline" size={20} color={colors.gray} />
                )}
              </View>
            ))}
          </View>
        </View>

        {/* Actions */}
        <View style={styles.actionContainer}>
          {!isPremium ? (
            <Pressable 
              style={({ pressed }) => [
                styles.upgradeButton,
                pressed && styles.buttonPressed
              ]}
              onPress={handleUpgrade}
            >
              <LinearGradient
                colors={colors.gradients.primary}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={styles.gradientButton}
              >
                <Text style={styles.upgradeButtonText}>Upgrade to Premium</Text>
                <Ionicons name="arrow-forward" size={20} color={colors.white} />
              </LinearGradient>
            </Pressable>
          ) : (
            <Pressable 
              style={({ pressed }) => [
                styles.manageButton,
                pressed && styles.buttonPressed
              ]}
              onPress={handleManageSubscription}
            >
              <Text style={styles.manageButtonText}>Manage Subscription</Text>
            </Pressable>
          )}

          <Pressable onPress={handleRestorePurchases} style={styles.restoreButton}>
            <Text style={styles.restoreButtonText}>Restore Purchases</Text>
          </Pressable>
        </View>
        
        {/* Footer Info */}
        <View style={styles.footer}>
            <Text style={styles.footerText}>
                Subscriptions auto-renew unless canceled at least 24 hours before the end of the current period.
            </Text>
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: colors.textSecondary,
    fontSize: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: colors.background,
  },
  backButton: {
    margin: 0,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  cardContainer: {
    marginBottom: 32,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  statusCard: {
    borderRadius: 24,
    padding: 24,
    minHeight: 160,
    justifyContent: 'space-between',
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1,
    marginBottom: 8,
  },
  statusTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.white,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  premiumInfo: {
    marginTop: 24,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginVertical: 12,
  },
  freeDescription: {
    marginTop: 16,
    fontSize: 15,
    lineHeight: 22,
    color: 'rgba(255,255,255,0.9)',
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 16,
  },
  featuresGrid: {
    gap: 16,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.secondary,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  featureIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  featureTextContent: {
    flex: 1,
    marginRight: 8,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  featureDescription: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  actionContainer: {
    gap: 16,
    marginBottom: 32,
  },
  upgradeButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  gradientButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    gap: 8,
  },
  upgradeButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  manageButton: {
    backgroundColor: colors.secondary,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  manageButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  restoreButton: {
    alignItems: 'center',
    padding: 12,
  },
  restoreButtonText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  footer: {
      alignItems: 'center',
      paddingHorizontal: 16,
  },
  footerText: {
      textAlign: 'center',
      color: colors.textTertiary,
      fontSize: 12,
      lineHeight: 18,
  }
});