-- Cardio exercises with timing-based parameters
-- Note: All cardio exercises use duration_seconds and rest_seconds instead of sets/reps

INSERT INTO exercises (
  name, 
  description, 
  category, 
  muscle_groups, 
  equipment, 
  difficulty, 
  instructions, 
  duration_seconds, 
  rest_seconds, 
  sets, 
  reps
) VALUES

-- Bodyweight Cardio Exercises
('Jumping Jacks', 
 'A classic full-body cardio exercise. Jump while spreading legs shoulder-width apart and raising arms overhead, then return to starting position.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'bodyweight', 
 'beginner', 
 ARRAY['Stand upright with legs together and arms at your sides', 'Jump while spreading legs shoulder-width apart', 'Simultaneously raise arms overhead', 'Jump back to starting position', 'Maintain a steady rhythm throughout'],
 30, 30, NULL, NULL),

('High Knees', 
 'Run in place while lifting knees as high as possible toward your chest. Great for building cardiovascular endurance.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'bodyweight', 
 'beginner', 
 ARRAY['Stand tall with feet hip-width apart', 'Run in place, lifting knees toward chest', 'Aim to bring knees to hip level or higher', 'Pump arms naturally as you run', 'Keep core engaged throughout'],
 30, 30, NULL, NULL),

('Burpees', 
 'A full-body explosive movement combining a squat, plank, push-up, and jump. Excellent for building strength and cardio endurance.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'bodyweight', 
 'intermediate', 
 ARRAY['Start in standing position', 'Drop into squat and place hands on floor', 'Jump feet back into plank position', 'Perform a push-up (optional)', 'Jump feet back to squat position', 'Explode up into a jump with arms overhead'],
 45, 45, NULL, NULL),

('Mountain Climbers', 
 'Start in plank position and alternate bringing knees toward chest in a running motion. Great core and cardio exercise.',
 'accessory', 
 ARRAY['cardio', 'core', 'arms'], 
 'bodyweight', 
 'intermediate', 
 ARRAY['Start in plank position with hands under shoulders', 'Bring right knee toward chest', 'Quickly switch legs, bringing left knee toward chest', 'Continue alternating in a running motion', 'Keep hips level and core engaged'],
 30, 30, NULL, NULL),

('Bear Crawls', 
 'Crawl forward on hands and feet with knees hovering just above ground. Excellent full-body cardio exercise.',
 'accessory', 
 ARRAY['cardio', 'full body', 'core'], 
 'bodyweight', 
 'intermediate', 
 ARRAY['Start on hands and knees', 'Lift knees 2 inches off ground', 'Crawl forward moving opposite hand and foot', 'Keep core tight and hips level', 'Maintain the knee hover throughout'],
 45, 45, NULL, NULL),

('Plank Jacks', 
 'Combine plank hold with jumping jack leg movement. Great for core strength and cardio conditioning.',
 'accessory', 
 ARRAY['cardio', 'core', 'arms'], 
 'bodyweight', 
 'intermediate', 
 ARRAY['Start in plank position', 'Jump feet wide apart while maintaining plank', 'Jump feet back together', 'Keep core engaged and hips stable', 'Maintain plank form throughout'],
 30, 30, NULL, NULL),

('Squat Jumps', 
 'Explosive jumping movement from squat position. Builds lower body power and cardiovascular fitness.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'bodyweight', 
 'intermediate', 
 ARRAY['Start in squat position', 'Explode up into a jump', 'Land softly back in squat position', 'Keep chest up and core engaged', 'Use arms for momentum and balance'],
 30, 30, NULL, NULL),

('Lateral Shuffles', 
 'Side-to-side shuffling movement staying low in athletic position. Great for agility and cardio.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'bodyweight', 
 'beginner', 
 ARRAY['Start in athletic stance', 'Shuffle to the right staying low', 'Keep feet wide and chest up', 'Shuffle back to the left', 'Maintain low position throughout'],
 30, 30, NULL, NULL),

-- Equipment-Based Cardio Exercises
('Jump Rope', 
 'Classic cardio exercise using a jump rope. Great for coordination, footwork, and cardiovascular fitness.',
 'accessory', 
 ARRAY['cardio', 'legs', 'arms'], 
 'jump rope', 
 'beginner', 
 ARRAY['Hold rope handles at hip level', 'Rotate rope with wrists, not arms', 'Jump on balls of feet', 'Keep jumps small and controlled', 'Maintain steady rhythm'],
 60, 30, NULL, NULL),

('Box Jumps', 
 'Jump onto a sturdy box or platform, then step back down. Builds explosive power and cardiovascular fitness.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'box/platform', 
 'intermediate', 
 ARRAY['Stand facing a sturdy box or platform', 'Squat slightly and swing arms back', 'Jump explosively onto the box', 'Land softly with both feet', 'Step back down carefully'],
 45, 45, NULL, NULL),

('Battle Ropes', 
 'High-intensity exercise using heavy ropes. Create waves with alternating or simultaneous arm movements.',
 'accessory', 
 ARRAY['cardio', 'arms', 'core'], 
 'battle ropes', 
 'advanced', 
 ARRAY['Stand with feet shoulder-width apart', 'Hold one rope end in each hand', 'Create waves by moving arms up and down', 'Keep core engaged throughout', 'Maintain consistent wave pattern'],
 30, 60, NULL, NULL),

('Kettlebell Swings', 
 'Dynamic exercise swinging a kettlebell from between legs to chest height. Great for posterior chain and cardio.',
 'accessory', 
 ARRAY['cardio', 'legs', 'core', 'back'], 
 'kettlebell', 
 'intermediate', 
 ARRAY['Stand with feet wider than shoulders', 'Hold kettlebell with both hands', 'Hinge at hips and swing kettlebell between legs', 'Drive hips forward to swing kettlebell to chest height', 'Let gravity bring kettlebell back down'],
 45, 45, NULL, NULL),

('Step-Ups', 
 'Step up onto a platform or bench, then step back down. Great for building leg strength and cardio endurance.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'bench/platform', 
 'beginner', 
 ARRAY['Stand facing a sturdy bench or platform', 'Step up with right foot, bringing left foot up', 'Step back down with the same foot', 'Alternate leading foot each set', 'Keep chest up and core engaged'],
 60, 30, NULL, NULL),

('Wall Balls', 
 'Throw a medicine ball against a wall from squat position. Combines strength training with cardio conditioning.',
 'accessory', 
 ARRAY['cardio', 'legs', 'arms', 'core'], 
 'medicine ball', 
 'intermediate', 
 ARRAY['Hold medicine ball at chest level', 'Squat down keeping ball close to chest', 'Explode up and throw ball to wall target', 'Catch ball on the way down', 'Immediately go into next squat'],
 45, 45, NULL, NULL),

('Thrusters', 
 'Combine front squat with overhead press using dumbbells or barbell. Full-body explosive movement.',
 'accessory', 
 ARRAY['cardio', 'legs', 'arms', 'core'], 
 'dumbbells', 
 'intermediate', 
 ARRAY['Hold dumbbells at shoulder level', 'Squat down keeping chest up', 'Drive up explosively through heels', 'Press weights overhead as you stand', 'Lower weights back to shoulders'],
 45, 45, NULL, NULL),

-- Machine-Based Cardio Exercises
('Treadmill Running', 
 'Steady-state or interval running on a treadmill. Adjust speed and incline for varying intensity.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'treadmill', 
 'beginner', 
 ARRAY['Start with 5-minute warm-up walk', 'Gradually increase to comfortable running pace', 'Maintain proper running posture', 'Use arms for momentum', 'Cool down with walking'],
 1200, 0, NULL, NULL),

('Rowing Machine', 
 'Full-body cardio exercise using a rowing machine. Great for building endurance and strength simultaneously.',
 'accessory', 
 ARRAY['cardio', 'full body', 'back', 'arms'], 
 'rowing machine', 
 'intermediate', 
 ARRAY['Sit on rowing machine with feet secured', 'Grab handle with overhand grip', 'Start with legs, then lean back, then pull arms', 'Reverse the motion: arms, lean forward, legs', 'Maintain steady stroke rate'],
 900, 0, NULL, NULL),

('Stationary Bike', 
 'Cycling exercise on a stationary bike. Low-impact cardio that''s easy on joints.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'stationary bike', 
 'beginner', 
 ARRAY['Adjust seat height to proper position', 'Start with light resistance', 'Maintain steady pedaling rhythm', 'Keep upper body relaxed', 'Gradually increase intensity as needed'],
 1800, 0, NULL, NULL),

('Elliptical Machine', 
 'Low-impact cardio exercise on an elliptical trainer. Great for those with joint issues.',
 'accessory', 
 ARRAY['cardio', 'legs', 'arms'], 
 'elliptical', 
 'beginner', 
 ARRAY['Step onto elliptical with feet on pedals', 'Grab handles and start slow movement', 'Gradually increase pace and resistance', 'Keep back straight and core engaged', 'Use both arms and legs for full-body workout'],
 1500, 0, NULL, NULL),

('Bike Sprints', 
 'High-intensity cycling intervals on stationary bike. Alternate between all-out sprints and recovery.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'stationary bike', 
 'advanced', 
 ARRAY['Warm up with 5 minutes easy cycling', 'Sprint at maximum effort', 'Maintain high cadence and resistance', 'Recover with easy pedaling', 'Cool down with light cycling'],
 30, 90, NULL, NULL),

-- Outdoor/Activity-Based Cardio
('Sprint Intervals', 
 'High-intensity running intervals. Run at maximum effort for short bursts followed by recovery periods.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'none', 
 'advanced', 
 ARRAY['Warm up with light jogging for 5 minutes', 'Sprint at 90-95% maximum effort', 'Focus on proper running form', 'Use arms to drive momentum', 'Cool down with walking between intervals'],
 60, 120, NULL, NULL),

('Stair Climbing', 
 'Running or walking up stairs for cardiovascular conditioning. Use actual stairs or stair climbing machine.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'stairs', 
 'intermediate', 
 ARRAY['Start at bottom of stairs', 'Run or walk up at steady pace', 'Use handrail for balance if needed', 'Take two steps at a time for intensity', 'Walk down for recovery'],
 300, 120, NULL, NULL),

('Dancing', 
 'Fun cardio workout through dance movements. Follow along with dance videos or freestyle.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'none', 
 'beginner', 
 ARRAY['Put on upbeat music', 'Start with simple movements', 'Add arm movements and footwork', 'Keep moving continuously', 'Have fun and express yourself'],
 1200, 0, NULL, NULL),

('Swimming', 
 'Full-body, low-impact cardio exercise in water. Excellent for cardiovascular fitness and muscle endurance.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'pool', 
 'intermediate', 
 ARRAY['Start with warm-up laps at easy pace', 'Choose your preferred stroke', 'Maintain steady breathing rhythm', 'Focus on proper technique', 'Cool down with easy swimming'],
 1800, 0, NULL, NULL),

-- HIIT Workouts
('HIIT Circuit', 
 'High-Intensity Interval Training combining multiple exercises. Alternate between high-intensity work and rest periods.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'bodyweight', 
 'advanced', 
 ARRAY['Choose 4-6 different exercises', 'Work at maximum effort for work period', 'Rest completely during rest periods', 'Repeat circuit 3-5 times', 'Cool down with light movement'],
 20, 10, NULL, NULL),

-- Additional Running and Cardio Machine Exercises
('Outdoor Running', 
 'Running outdoors on various terrains. Great for cardiovascular fitness and mental health benefits of fresh air.',
 'accessory', 
 ARRAY['cardio', 'legs', 'core'], 
 'none', 
 'beginner', 
 ARRAY['Start with a 5-minute walking warm-up', 'Begin at comfortable jogging pace', 'Maintain good posture with relaxed shoulders', 'Land on midfoot, not heel', 'Cool down with 5-minute walk'],
 1800, 0, NULL, NULL),

('Treadmill Walking Incline', 
 'Walking on treadmill with incline for low-impact cardio that''s easier on joints than running.',
 'accessory', 
 ARRAY['cardio', 'legs', 'glutes'], 
 'treadmill', 
 'beginner', 
 ARRAY['Set treadmill to 3-8% incline', 'Walk at brisk but comfortable pace', 'Keep shoulders back and core engaged', 'Use handrails only for balance', 'Gradually increase incline as fitness improves'],
 2400, 0, NULL, NULL),

('Treadmill Intervals', 
 'Alternating between high-intensity running and recovery periods on treadmill.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'treadmill', 
 'intermediate', 
 ARRAY['Warm up with 5-minute easy walk/jog', 'Run at high intensity for work interval', 'Recover with walking or light jogging', 'Repeat interval pattern 5-8 times', 'Cool down with 5-minute walk'],
 120, 120, NULL, NULL),

-- Swimming Variations
('Pool Running', 
 'Running in deep water while wearing a flotation belt. Excellent low-impact cardio for injury recovery.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'pool', 
 'intermediate', 
 ARRAY['Wear a flotation belt in deep water', 'Maintain running motion without touching bottom', 'Keep upright posture and pump arms', 'Lean slightly forward and drive knees up', 'Maintain steady breathing rhythm'],
 1200, 0, NULL, NULL),

('Freestyle Swimming', 
 'Front crawl swimming stroke focusing on technique and endurance. Most popular and efficient swimming stroke.',
 'accessory', 
 ARRAY['cardio', 'shoulders', 'back', 'core'], 
 'pool', 
 'intermediate', 
 ARRAY['Start with streamlined push off from wall', 'Rotate body with each stroke', 'Keep head in neutral position', 'Breathe every 2-3 strokes to one side', 'Maintain steady kick throughout'],
 1200, 0, NULL, NULL),

('Swimming Laps Mixed Strokes', 
 'Swimming different strokes (freestyle, backstroke, breaststroke) for varied muscle engagement.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'pool', 
 'intermediate', 
 ARRAY['Swim 1-2 laps of freestyle', 'Switch to backstroke for 1-2 laps', 'Try breaststroke for variety', 'Rest briefly at wall between stroke changes', 'Focus on proper technique over speed'],
 1800, 0, NULL, NULL),

('Water Aerobics', 
 'Low-impact aerobic exercises performed in shallow water. Great for all fitness levels and joint-friendly.',
 'accessory', 
 ARRAY['cardio', 'full body'], 
 'pool', 
 'beginner', 
 ARRAY['Stand in chest-deep water', 'Perform marching, jumping jacks, or leg lifts', 'Use water resistance for arm movements', 'Keep movements controlled and steady', 'Follow along with instructor or routine'],
 1800, 0, NULL, NULL),

-- Gym Cardio Machines
('Cross Trainer', 
 'Full-body cardio workout on cross trainer/elliptical with adjustable resistance and incline.',
 'accessory', 
 ARRAY['cardio', 'legs', 'arms'], 
 'cross trainer', 
 'beginner', 
 ARRAY['Step onto machine and grab moving handles', 'Start with slow, controlled movements', 'Gradually increase pace and resistance', 'Keep back straight and core engaged', 'Coordinate arms and legs smoothly'],
 1800, 0, NULL, NULL),

('StairMaster', 
 'Climbing machine that simulates stair climbing for intense lower body and cardio workout.',
 'accessory', 
 ARRAY['cardio', 'legs', 'glutes'], 
 'stairmaster', 
 'intermediate', 
 ARRAY['Step onto machine and set comfortable pace', 'Keep full foot contact on each step', 'Stand upright, avoid leaning on handrails', 'Take full steps, don''t just tap toes', 'Maintain steady rhythm throughout'],
 1200, 0, NULL, NULL),

('Spin Bike', 
 'High-intensity indoor cycling on specialized stationary bike with adjustable resistance.',
 'accessory', 
 ARRAY['cardio', 'legs', 'core'], 
 'spin bike', 
 'intermediate', 
 ARRAY['Adjust seat height and handlebar position', 'Start with moderate resistance', 'Maintain proper cycling posture', 'Vary between seated and standing positions', 'Follow instructor cues or personal interval plan'],
 2700, 0, NULL, NULL),

('Recumbent Bike', 
 'Low-impact cycling exercise on recumbent bike with back support. Great for those with back issues.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'recumbent bike', 
 'beginner', 
 ARRAY['Adjust seat so knees are slightly bent at full extension', 'Sit back comfortably against backrest', 'Start pedaling at easy resistance', 'Maintain steady rhythm without bouncing', 'Gradually increase resistance as needed'],
 2400, 0, NULL, NULL),

('Arc Trainer', 
 'Low-impact cardio machine combining elements of elliptical and stair climber for total body workout.',
 'accessory', 
 ARRAY['cardio', 'legs', 'glutes', 'arms'], 
 'arc trainer', 
 'intermediate', 
 ARRAY['Step onto foot plates and grab handles', 'Start with slow arc motion', 'Adjust incline for desired intensity', 'Keep core engaged throughout movement', 'Coordinate upper and lower body smoothly'],
 1500, 0, NULL, NULL),

-- Additional Cardio Options
('Jogging in Place', 
 'Simple cardio exercise that can be done anywhere. Great for warming up or quick cardio bursts.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'none', 
 'beginner', 
 ARRAY['Stand with feet hip-width apart', 'Begin jogging motion staying in place', 'Lift knees to comfortable height', 'Land softly on balls of feet', 'Pump arms naturally for balance'],
 300, 60, NULL, NULL),

('Shadowboxing', 
 'Boxing movements performed without equipment. Great cardio workout that improves coordination.',
 'accessory', 
 ARRAY['cardio', 'arms', 'core'], 
 'none', 
 'intermediate', 
 ARRAY['Stand in boxing stance with guard up', 'Throw combinations of punches', 'Keep moving and bouncing on feet', 'Add defensive movements like slips and ducks', 'Maintain high intensity throughout'],
 180, 60, NULL, NULL),

('Track Running', 
 'Running on a track for precise distance and pace control. Ideal for speed work and interval training.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'track', 
 'intermediate', 
 ARRAY['Warm up with easy jogging', 'Run in lane 1 for accurate distance', 'Maintain steady pace for distance runs', 'Use inner lanes for speed work', 'Cool down with walking or light jogging'],
 1200, 0, NULL, NULL),

('Hill Running', 
 'Running uphill for increased intensity and strength building. Excellent for building power and endurance.',
 'accessory', 
 ARRAY['cardio', 'legs', 'glutes'], 
 'none', 
 'advanced', 
 ARRAY['Find a hill with 4-8% grade', 'Run up at steady, controlled effort', 'Shorten stride and increase cadence', 'Pump arms more vigorously uphill', 'Walk or jog down for recovery'],
 120, 180, NULL, NULL),

('Fartlek Training', 
 'Swedish speed play combining continuous running with interval training. Mix fast and slow segments.',
 'accessory', 
 ARRAY['cardio', 'legs'], 
 'none', 
 'intermediate', 
 ARRAY['Start with 10-minute easy run', 'Add random speed bursts during run', 'Sprint to landmarks or for set times', 'Recover with easy jogging between efforts', 'Keep total session playful and unstructured'],
 1800, 0, NULL, NULL)

ON CONFLICT (name) DO NOTHING;

-- Create index on category if it doesn't exist
CREATE INDEX IF NOT EXISTS idx_exercises_category ON exercises(category);

-- Create index on muscle_groups for better filtering performance
CREATE INDEX IF NOT EXISTS idx_exercises_muscle_groups ON exercises USING GIN(muscle_groups);

-- Verify the cardio exercises were inserted
SELECT COUNT(*) as cardio_exercise_count FROM exercises WHERE category = 'cardio';
